# Generated by Django 3.2.10 on 2023-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_productdb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Googlemap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
