# Generated by Django 3.2.10 on 2023-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_productdb_googlemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
