# Generated by Django 3.2.10 on 2023-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_remove_productdb_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
