# Generated by Django 3.2.10 on 2023-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_selldb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Propertyplace', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Bedrooms', models.IntegerField(blank=True, null=True)),
                ('Bathrooms', models.IntegerField(blank=True, null=True)),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='properties')),
            ],
        ),
    ]
