# Generated by Django 3.2.10 on 2023-08-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_wishlistdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistdb',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist'),
        ),
    ]
