# Generated by Django 3.2.10 on 2023-08-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_wishlistdb_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Image1',
        ),
    ]
