# Generated by Django 3.2.10 on 2023-08-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_remove_wishlistdb_image1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistDB',
        ),
    ]
