# Generated by Django 3.2.10 on 2023-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_delete_wishlistdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Propertyplace', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Bedrooms', models.IntegerField(blank=True, null=True)),
                ('Bathrooms', models.IntegerField(blank=True, null=True)),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
