# Generated by Django 3.2.10 on 2023-09-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_contactdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Image',
        ),
    ]
