# Generated by Django 3.2.10 on 2023-09-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_wishlistdb_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Image1',
        ),
    ]
