# Generated by Django 3.2.10 on 2023-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_alter_registrationdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
