# Generated by Django 3.2.10 on 2023-09-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_auto_20230905_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryDB',
        ),
    ]
