# Generated by Django 3.2.10 on 2023-09-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
