# Generated by Django 3.2.10 on 2023-09-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Image1',
        ),
    ]
