# Generated by Django 3.2.10 on 2023-09-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0020_wishlistdb_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Category_Name',
        ),
    ]
