# Generated by Django 3.2.10 on 2023-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0021_remove_wishlistdb_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Message1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Message2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
