# Generated by Django 3.2.10 on 2023-09-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0022_auto_20230907_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Message1',
        ),
        migrations.RemoveField(
            model_name='registrationdb',
            name='Message2',
        ),
    ]
