# Generated by Django 3.2.10 on 2023-09-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0023_auto_20230907_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='Mobile',
            new_name='Mobile_User',
        ),
    ]
