# Generated by Django 3.2.10 on 2023-09-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0024_rename_mobile_registrationdb_mobile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selldb',
            old_name='Mobile',
            new_name='Mobile_User',
        ),
    ]
