# Generated by Django 3.2.10 on 2023-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0026_rename_mobile_user_selldb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Suggestion', models.CharField(blank=True, max_length=200, null=True)),
                ('Rating1', models.IntegerField(blank=True, null=True)),
                ('Rating2', models.IntegerField(blank=True, null=True)),
                ('Rating3', models.IntegerField(blank=True, null=True)),
                ('Rating4', models.IntegerField(blank=True, null=True)),
                ('Rating5', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrationdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
