# Generated by Django 3.2.10 on 2023-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0027_auto_20230908_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdb',
            name='Rating1',
        ),
        migrations.RemoveField(
            model_name='ratingdb',
            name='Rating2',
        ),
        migrations.RemoveField(
            model_name='ratingdb',
            name='Rating3',
        ),
        migrations.RemoveField(
            model_name='ratingdb',
            name='Rating4',
        ),
        migrations.RemoveField(
            model_name='ratingdb',
            name='Rating5',
        ),
        migrations.AddField(
            model_name='ratingdb',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
