# Generated by Django 3.2.10 on 2023-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0028_auto_20230908_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdb',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
