# Generated by Django 3.2.10 on 2023-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0029_alter_ratingdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='User_pic'),
        ),
    ]
