# Generated by Django 3.2.10 on 2023-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0030_registrationdb_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdb',
            name='Address',
        ),
        migrations.AddField(
            model_name='ratingdb',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='rating'),
        ),
    ]
