# Generated by Django 3.2.10 on 2023-09-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0032_enquirydb_mobile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='Agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
