# Generated by Django 3.2.10 on 2023-09-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0033_enquirydb_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydb',
            name='Agent_name',
        ),
    ]
