# Generated by Django 3.2.10 on 2023-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0036_rename_message1_enquirydb_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdb',
            name='Profile_Pic',
        ),
    ]
