# Generated by Django 3.2.10 on 2023-09-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0037_remove_ratingdb_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
