# Generated by Django 3.2.10 on 2023-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0038_alter_registrationdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDB',
            fields=[
                ('Bookingid', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_User', models.IntegerField(blank=True, null=True)),
                ('Mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
