# Generated by Django 3.2.10 on 2023-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0040_bookingdb_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
