# Generated by Django 3.2.10 on 2023-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0041_auto_20230912_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Property_Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
