# Generated by Django 3.2.10 on 2023-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0043_alter_bookingdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Bookingid',
            field=models.AutoField(default=2000, primary_key=True, serialize=False),
        ),
    ]
