# Generated by Django 3.2.10 on 2023-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0044_alter_bookingdb_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Bookingid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
