# Generated by Django 3.2.10 on 2023-09-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0046_alter_bookingdb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Agent_Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Agent_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
