# Generated by Django 3.2.10 on 2023-09-12 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0047_auto_20230912_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_User', models.IntegerField(blank=True, null=True)),
                ('Mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Property_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Agent_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Agent_Mobile', models.IntegerField(blank=True, null=True)),
                ('Bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.bookingdb')),
            ],
        ),
    ]
