# Generated by Django 3.2.10 on 2023-09-12 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0048_paymentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='CVV',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Card_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Expiry_date',
            field=models.CharField(help_text='Format: MM/YY', max_length=5, null=True),
        ),
    ]
