# Generated by Django 3.2.10 on 2023-09-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0049_auto_20230912_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='Booking_date',
        ),
    ]
