# Generated by Django 3.2.10 on 2023-09-12 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0050_remove_paymentdb_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
