# Generated by Django 3.2.10 on 2023-09-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0051_paymentdb_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='Bookingid',
        ),
    ]
