# Generated by Django 3.2.10 on 2023-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0053_alter_selldb_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Bookingid',
            field=models.AutoField(default=3000, primary_key=True, serialize=False),
        ),
    ]
