# Generated by Django 3.2.10 on 2023-09-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0054_alter_bookingdb_bookingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='id',
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Bookingid',
            field=models.ForeignKey(default=3000, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Frontend.bookingdb'),
        ),
    ]
