# Generated by Django 3.2.10 on 2023-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0055_auto_20230913_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Bookingid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PaymentDB',
        ),
    ]
