# Generated by Django 3.2.10 on 2023-09-13 09:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0056_auto_20230913_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_User', models.IntegerField(blank=True, null=True)),
                ('Mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Property_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Agent_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Agent_Mobile', models.IntegerField(blank=True, null=True)),
                ('Card_number', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('Expiry_date', models.CharField(help_text='Format: MM/YY', max_length=5, null=True)),
                ('CVV', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
            ],
        ),
    ]
