# Generated by Django 3.2.10 on 2023-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0057_paymentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Visit_date', models.DateField()),
                ('Visit_time', models.TimeField()),
                ('Mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
