# Generated by Django 3.2.10 on 2023-09-13 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0058_visitdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdb',
            name='Current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
