# Generated by Django 3.2.10 on 2023-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0059_visitdb_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdb',
            name='Property_Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
