# Generated by Django 3.2.10 on 2023-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0060_visitdb_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='Expiry_date',
            field=models.DateField(help_text='Format: MM/YY', null=True),
        ),
    ]
